//
//  Constants.swift
//
//  Created by Gavin Eadie on 1/18/23.
//

let LOGMSGLEN   =  128
let FILEPATHLEN =  512
let GETSETSTRLEN = 512
let INFOSTRLEN  =  128
let INPUTCARDLEN = 512

// ASTRO ----------------------------------------------------------------------

// INDEX OF KEPLERIAN ELEMENTS
let XA_KEP_A     =   0       // SEMI-MAJOR AXIS (KM)
let XA_KEP_E     =   1       // ECCENTRICITY (UNITLESS)
let XA_KEP_INCLI =   2       // INCLINATION (DEG)
let XA_KEP_MA    =   3       // MEAN ANOMALY (DEG)
let XA_KEP_NODE  =   4       // RIGHT ASCENSION OF THE ASENDING NODE (DEG)
let XA_KEP_OMEGA =   5       // ARGUMENT OF PERIGEE (DEG)
let XA_KEP_SIZE  =  6

// INDEX OF CLASSICAL ELEMENTS
let XA_CLS_N     =   0       // N MEAN MOTION (REVS/DAY)
let XA_CLS_E     =   1       // ECCENTRICITY (UNITLESS)
let XA_CLS_INCLI =   2       // INCLINATION (DEG)
let XA_CLS_MA    =   3       // MEAN ANOMALY (DEG)
let XA_CLS_NODE  =   4       // RIGHT ASCENSION OF THE ASENDING NODE (DEG)
let XA_CLS_OMEGA =   5       // ARGUMENT OF PERIGEE (DEG)
let XA_CLS_SIZE  =   6

// INDEX OF EQUINOCTIAL ELEMENTS
let XA_EQNX_AF   =   0       // AF (UNITLESS)
let XA_EQNX_AG   =   1       // AG (UNITLESS)
let XA_EQNX_CHI  =   2       // CHI (UNITLESS)
let XA_EQNX_PSI  =   3       // PSI (UNITLESS)
let XA_EQNX_L    =   4       // L MEAN LONGITUDE (DEG)
let XA_EQNX_N    =   5       // N MEAN MOTION (REVS/DAY)
let XA_EQNX_SIZE =   6

  // INDEXES OF ASTROCONVFRTO
let XF_CONV_SGP42SGP = 101        // SGP4 (A E INCLI BSTAR) TO SGP (NDOT N2DOT)


  // INDEXES FOR TOPOCENTRIC COMPONENTS
let XA_TOPO_RA    = 0         // RIGHT ASCENSION (DEG)
let XA_TOPO_DEC   = 1         // DECLINATION (DEG)
let XA_TOPO_AZ    = 2         // AZIMUTH (DEG)
let XA_TOPO_EL    = 3         // ELEVATION (DEG)
let XA_TOPO_RANGE = 4         // RANGE (KM)
let XA_TOPO_RADOT = 5         // RIGHT ASCENSION DOT (DEG/S)
let XA_TOPO_DECDOT = 6         // DECLINCATION DOT (DEG/S)
let XA_TOPO_AZDOT = 7         // AZIMUTH DOT (DEG/S)
let XA_TOPO_ELDOT = 8         // ELEVATION DOT (DEG/S)
let XA_TOPO_RANGEDOT = 9      // RANGE DOT (KM/S)
let XA_TOPO_SIZE  = 10


  // INDEXES FOR RAE COMPONENTS
let XA_RAE_RANGE   = 0        // RANGE (KM)
let XA_RAE_AZ      = 1        // AZIMUTH (DEG)
let XA_RAE_EL      = 2        // ELEVATION (DEG)
let XA_RAE_RANGEDOT = 3        // RANGE DOT (KM/S)
let XA_RAE_AZDOT   = 4        // AZIMUTH DOT (DEG/S)
let XA_RAE_ELDOT   = 5        // ELEVATION DOT (DEG/S)
let XA_RAE_SIZE    = 6


  // YEAR OF EQUINOX INDICATOR
let YROFEQNX_OBTIME = 0       // DATE OF OBSERVATION
let YROFEQNX_CURR   = 1       // 0 JAN OF DATE
let YROFEQNX_2000   = 2       // J2000
let YROFEQNX_1950   = 3       // B1950

// DLLMAIN --------------------------------------------------------------------

  // ELEMENT TYPES (LAST DIGIT OF SATKEY)
let ELTTYPE_DMA       = 0    // DIRECT MEMORY ACCESS
let ELTTYPE_TLE_SGP   = 1    // ELEMENT TYPE - SGP TLE TYPE 0
let ELTTYPE_TLE_SGP4  = 2    // ELEMENT TYPE - SGP4 TLE TYPE 2
let ELTTYPE_TLE_SP    = 3    // ELEMENT TYPE - SP TLE TYPE 6
let ELTTYPE_SPVEC_B1P = 4    // ELEMENT TYPE - SP VECTOR
let ELTTYPE_VCM       = 5    // ELEMENT TYPE - VCM
let ELTTYPE_EXTEPH    = 6    // ELEMENT TYPE - EXTERNAL EPHEMERIS
let ELTTYPE_TLE_XP    = 7    // ELEMENT TYPE - SGP TLE TYPE 4 - XP

  //*******************************************************************************

  // ORBITAL ELSET TYPES
let OET_TLE_SGP   = 1    // ORBITAL ELSET TYPE - SGP TLE TYPE 0
let OET_TLE_SGP4  = 2    // ORBITAL ELSET TYPE - SGP4 TLE TYPE 2
let OET_TLE_SP    = 3    // ORBITAL ELSET TYPE - SP TLE TYPE 6
let OET_SPVEC_B1P = 4    // ORBITAL ELSET TYPE - SP VECTOR
let OET_VCM       = 5    // ORBITAL ELSET TYPE - VCM
let OET_EXTEPH    = 6    // ORBITAL ELSET TYPE - EXTERNAL EPHEMERIS
let OET_TLE_XP    = 7    // ORBITAL ELSET TYPE - SGP TLE TYPE 4 - XP

  //*******************************************************************************

  // PROPAGATION TYPES
let PROPTYPE_GP  = 1       // GP/SGP4/SGP4-XP PROPAGATOR
let PROPTYPE_SP  = 2       // SP PROPAGATOR
let PROPTYPE_X   = 3       // EXTERNAL EPHEMERIS
let PROPTYPE_UK  = 4       // UNKNOWN
  //*******************************************************************************

  // ADD SAT ERROR
let BADSATKEY = -1      // BAD SATELLITE KEY
let DUPSATKEY =  0      // DUPLICATE SATELLITE KEY

  //*******************************************************************************

  // OPTIONS USED IN GETLOADED()
let IDX_ORDER_ASC   = 0    // ASCENDING ORDER
let IDX_ORDER_DES   = 1    // DESCENDING ORDER
let IDX_ORDER_READ  = 2    // ORDER AS READ
let IDX_ORDER_QUICK = 9    // TREE TRAVERSAL ORDER

  //*******************************************************************************

  // DIFFERENT KEY MODE OPTIONS FOR ELSET SATKEY
let ELSET_KEYMODE_NODUP  = 0    // DEFAULT - DUPLICATE ELSETS CAN NOT BE LOADED IN BINARY TREE
let ELSET_KEYMODE_DMA    = 1    // ALLOW DUPLICATE ELSETS TO BE LOADED AND HAVE DIRECT MEMORY ACCESS (DMA - NO DUPLICATION CHECK AND NO BINARY TREE)

  //*******************************************************************************

// ENV --------------------------------------------------------------------

  // INDEXES OF EARTH CONSTANT FIELDS
let XF_GEOCON_FF    = 1         // EARTH FLATTENING (RECIPROCAL UNITLESS)
let XF_GEOCON_J2    = 2         // J2 (UNITLESS)
let XF_GEOCON_J3    = 3         // J3 (UNITLESS)
let XF_GEOCON_J4    = 4         // J4 (UNITLESS)
let XF_GEOCON_KE    = 5         // KE (ER**1.5/MIN)
let XF_GEOCON_KMPER = 6         // EARTH RADIUS (KM/ER)
let XF_GEOCON_RPTIM = 7         // EARTH ROTATION RATE W.R.T. FIXED EQUINOX (RAD/MIN)

let XF_GEOCON_CK2   = 8         // J2/2 (UNITLESS)
let XF_GEOCON_CK4   = 9         // -3/8 J4 (UNITLESS)
let XF_GEOCON_KS2EK = 10        // CONVERTS KM/SEC TO ER/KEM
let XF_GEOCON_THDOT = 11        // EARTH ROTATION RATE W.R.T. FIXED EQUINOX (RAD/KEMIN)
let XF_GEOCON_J5    = 12        // J5 (UNITLESS)


  // INDEXES OF FK CONSTANT FIELDS
let XF_FKCON_C1     = 1         // EARTH ROTATION RATE W.R.T. MOVING EQUINOX (RAD/DAY)
let XF_FKCON_C1DOT  = 2         // EARTH ROTATION ACCELERATION(RAD/DAY**2)
let XF_FKCON_THGR70 = 3         // GREENWICH ANGLE (1970 RAD)

  // INDEXES REPRESENT GEOPOTENTIAL MODELS GEO
let XF_GEOMOD_WGS84  =   84     // EARTH CONSTANTS - WGS-84
let XF_GEOMOD_EGM96  =   96     // EARTH CONSTANTS - EGM-96
let XF_GEOMOD_EGM08  =    8     // EARTH CONSTANTS - EGM-08
let XF_GEOMOD_WGS72  =   72     // EARTH CONSTANTS - WGS-72
let XF_GEOMOD_JGM2   =    2     // EARTH CONSTANTS - JGM2
let XF_GEOMOD_STEM68 =   68     // EARTH CONSTANTS - STEM68
let XF_GEOMOD_GEM5   =    5     // EARTH CONSTANTS - GEM5
let XF_GEOMOD_GEM9   =    9     // EARTH CONSTANTS - GEM9
let XF_GEOMOD_UNKNOWN =  100     // INVALID EARTH MODEL

  //*******************************************************************************

  // INDEXES REPRESENT FUNDAMENTAL CATALOGUE FK
let XF_FKMOD_4 = 4    // FUNDAMENTAL CATALOG - FK5
let XF_FKMOD_5 = 5    // FUNDAMENTAL CATALOG - FK4

// SGP4 ---------

  // DIFFERENT TIME TYPES FOR PASSING TO SGP4PROPALL
let SGP4_TIMETYPE_MSE      = 0   // PROPAGATION TIME IS IN MINUTES SINCE EPOCH
let SGP4_TIMETYPE_DS50UTC  = 1   // PROPAGATION TIME IS IN DAYS SINCE 1950 UTC

  // SGP4 PROPAGATED OUTPUT FIELDS
let XF_SGP4OUT_REVNUM       = 1    // REVOLUTION NUMBER
let XF_SGP4OUT_NODAL_AP_PER = 2    // NODAL PERIOD APOGEE PERIGEE
let XF_SGP4OUT_MEAN_KEP     = 3    // MEAN KEPLERIAN
let XF_SGP4OUT_OSC_KEP      = 4    // OSCULATING KEPLERIAN

  // SGP4 PROPAGATED DATA
let XA_SGP4OUT_DS50UTC      =  0   // PROPAGATION TIME IN DAYS SINCE 1950 UTC
let XA_SGP4OUT_MSE          =  1   // PROPAGATION TIME IN MINUTES SINCE THE SATELLITE'S EPOCH TIME
let XA_SGP4OUT_POSX         =  2   // ECI X POSITION (KM) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_POSY         =  3   // ECI Y POSITION (KM) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_POSZ         =  4   // ECI Z POSITION (KM) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_VELX         =  5   // ECI X VELOCITY (KM/S) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_VELY         =  6   // ECI Y VELOCITY (KM/S) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_VELZ         =  7   // ECI Z VELOCITY (KM/S) IN TRUE EQUATOR AND MEAN EQUINOX OF EPOCH
let XA_SGP4OUT_LAT          =  8   // GEODETIC LATITUDE (DEG)
let XA_SGP4OUT_LON          =  9   // GEODETIC LONGITUDE (DEG)
let XA_SGP4OUT_HEIGHT       = 10   // HEIGHT ABOVE GEOID (KM)
let XA_SGP4OUT_REVNUM       = 11   // REVOLUTION NUMBER
let XA_SGP4OUT_NODALPER     = 12   // NODAL PERIOD (MIN)
let XA_SGP4OUT_APOGEE       = 13   // APOGEE (KM)
let XA_SGP4OUT_PERIGEE      = 14   // PERIGEE (KM)
let XA_SGP4OUT_MN_A         = 15   // MEAN SEMI-MAJOR AXIS (KM)
let XA_SGP4OUT_MN_E         = 16   // MEAN ECCENTRICITY (UNITLESS)
let XA_SGP4OUT_MN_INCLI     = 17   // MEAN INCLINATION (DEG)
let XA_SGP4OUT_MN_MA        = 18   // MEAN MEAN ANOMALY (DEG)
let XA_SGP4OUT_MN_NODE      = 19   // MEAN RIGHT ASCENSION OF THE ASENDING NODE (DEG)
let XA_SGP4OUT_MN_OMEGA     = 20   // MEAN ARGUMENT OF PERIGEE (DEG)
let XA_SGP4OUT_OSC_A        = 21   // OSCULATING SEMI-MAJOR AXIS (KM)
let XA_SGP4OUT_OSC_E        = 22   // OSCULATING ECCENTRICITY (UNITLESS)
let XA_SGP4OUT_OSC_INCLI    = 23   // OSCULATING INCLINATION (DEG)
let XA_SGP4OUT_OSC_MA       = 24   // OSCULATING MEAN ANOMALY (DEG)
let XA_SGP4OUT_OSC_NODE     = 25   // OSCULATING RIGHT ASCENSION OF THE ASENDING NODE (DEG)
let XA_SGP4OUT_OSC_OMEGA    = 26   // OSCULATING ARGUMENT OF PERIGEE (DEG)

let XA_SGP4OUT_SIZE         = 64

  // DIFFERENT OPTIONS FOR GENERATING EPHEMERIDES FROM SGP4
let SGP4_EPHEM_ECI   = 1       // ECI TEME OF DATE     - 0: TIME IN DAYS SINCE 1950 UTC 1-3: POS (KM) 4-6: VEL (KM/SEC)
let SGP4_EPHEM_J2K   = 2       // MEME OF J2K (4 TERMS)- 0: TIME IN DAYS SINCE 1950 UTC 1-3: POS (KM) 4-6: VEL (KM/SEC)


  // DIFFERENT DYNAMIC STEP SIZE OPTIONS
let DYN_SS_BASIC  = -1    // USE A SIMPLE ALGORITHM TO DETERMINE STEP SIZE BASED ON SATELLITE'S CURRENT POSITION

  //*******************************************************************************


  // DIFFERENT RETURN VALUES OF ERRCODE FROM SGP4 PROPAGATION
let GP_ERR_NONE        = 0    // SGP4 PROPAGATES SUCCESSFULLY
let GP_ERR_BADFK       = 1    // BAD FK MODEL (FK5 MUST BE SELECTED)
let GP_ERR_ANEGATIVE   = 2    // A IS NEGATIVE
let GP_ERR_ATOOLARGE   = 3    // A IS TO LARGE
let GP_ERR_EHYPERPOLIC = 4    // ECCENTRICITY IS HYPERBOLIC
let GP_ERR_ENEGATIVE   = 5    // ECCENTRICITY IS NEGATIVE
let GP_ERR_MATOOLARGE  = 6    // MEAN ANOMALY IS TOO LARGE
let GP_ERR_E2TOOLARGE  = 7    // E**2 IS TOO LARGE


  //*******************************************************************************

// TIME --------------

// TLE --------------

  // TLE TYPES (TLE EPHEMERIS TYPES) - THEY ARE DIFFERENT THAN ELTTYPE
let TLETYPE_SGP  = 0    // TLE SGP ELSET (KOZAI MEAN MOTION)
let TLETYPE_SGP4 = 2    // TLE SGP4 ELSET (BROUWER MEAN MOTION)
let TLETYPE_XP   = 4    // TLE SGP4-XP ELSET (BROUWER MEAN MOTION)
let TLETYPE_SP   = 6    // TLE SP ELSET (OSCULATING ELEMENTS)

  // INDEXES OF TLE DATA FIELDS
let XF_TLE_SATNUM     =  1    // SATELLITE NUMBER
let XF_TLE_CLASS      =  2    // SECURITY CLASSIFICATION U: UNCLASS C: CONFIDENTIAL S: SECRET
let XF_TLE_SATNAME    =  3    // SATELLITE NAME A8
let XF_TLE_EPOCH      =  4    // SATELLITE'S EPOCH TIME "YYYYJJJ.JJJJJJJJ"
let XF_TLE_BSTAR      =  5    // GP B* DRAG TERM (1/ER)  (NOT THE SAME AS XF_TLE_BTERM)
let XF_TLE_EPHTYPE    =  6    // SATELLITE EPHEMERIS TYPE: 0=SGP 2=SGP4 6=SP
let XF_TLE_ELSETNUM   =  7    // ELEMENT SET NUMBER
let XF_TLE_INCLI      =  8    // ORBIT INCLINATION (DEG)
let XF_TLE_NODE       =  9    // RIGHT ASCENSION OF ASENDING NODE (DEG)
let XF_TLE_ECCEN      = 10    // ECCENTRICITY
let XF_TLE_OMEGA      = 11    // ARGUMENT OF PERIGEE (DEG)
let XF_TLE_MNANOM     = 12    // MEAN ANOMALY (DEG)
let XF_TLE_MNMOTN     = 13    // MEAN MOTION (REV/DAY) (EPHTYPE=0: KOZAI EPHTYPE=2: BROUWER)
let XF_TLE_REVNUM     = 14    // REVOLUTION NUMBER AT EPOCH

let XF_TLE_NDOT       = 15    // GP MEAN MOTION DERIVATIVE (REV/DAY /2)
let XF_TLE_NDOTDOT    = 16    // GP MEAN MOTION SECOND DERIVATIVE (REV/DAY**2 /6)
let XF_TLE_AGOMGP     = 16    // SOLAR RADIATION PRESSURE GP (M2/KG)

let XF_TLE_SP_AGOM    =  5    // SP RADIATION PRESSURE COEFFICIENT
let XF_TLE_SP_BTERM   = 15    // SP BALLISTIC COEFFICIENT (M2/KG)
let XF_TLE_SP_OGPARM  = 16    // SP OUTGASSING PARAMETER (KM/S2)

let XF_TLE_ORGSATNUM  = 17    // ORIGINAL SATELLITE NUMBER
let XF_TLE_BTERM      = 18    // GP BALLISTIC COEFFICIENT (M2/KG) (NOT THE SAME AS XF_TLE_BSTAR)
let XF_TLE_OBSTIME    = 19    // TIME OF LAST OBSERVATION RELATIVE TO EPOCH +/- FRACTIONAL DAYS
let XF_TLE_EGR        = 20    // LAST CALCULATED ERROR GROWTH RATE (KM/DAY)
let XF_TLE_EDR        = 21    // LAST CALCULATED ENERGY DISSIPATION RATE (W/KG)
let XF_TLE_VISMAG     = 22    // MEDIAN VISMAG
let XF_TLE_RCS        = 23    // MEDIAN RCS - DIAMETER IN CENTIMETERS (CM)
let XF_TLE_OBJTYPE    = 24    // OBJECT TYPE (PAYLOAD ROCKET BODY PLATFORM DEBRIS UNKNOWN)
let XF_TLE_SATNAME_12 = 25    // SATELLITE NAME A12 (UPTO 12 CHARACTER LONG)


  // INDEXES OF TLE NUMERICAL DATA IN AN ARRAY
// LINE 1
let XA_TLE_SATNUM        =  0    // SATELLITE NUMBER
let XA_TLE_EPOCH         =  1    // SATELLITE'S EPOCH TIME IN DS50UTC
let XA_TLE_NDOT          =  2    // GP MEAN MOTION DERIVATIVE (REV/DAY /2)
let XA_TLE_NDOTDOT       =  3    // GP MEAN MOTION SECOND DERIVATIVE (REV/DAY**2 /6)
let XA_TLE_BSTAR         =  4    // GP B* DRAG TERM (1/ER)
let XA_TLE_EPHTYPE       =  5    // SATELLITE EPHEMERIS TYPE: 0=SGP 2=SGP4 4=SGP4-XP 6=SP

// LINE 2
let XA_TLE_INCLI         = 20    // ORBIT INCLINATION (DEG)
let XA_TLE_NODE          = 21    // RIGHT ASCENSION OF ASENDING NODE (DEG)
let XA_TLE_ECCEN         = 22    // ECCENTRICITY
let XA_TLE_OMEGA         = 23    // ARGUMENT OF PERIGEE (DEG)
let XA_TLE_MNANOM        = 24    // MEAN ANOMALY (DEG)
let XA_TLE_MNMOTN        = 25    // MEAN MOTION (REV/DAY) (EPHTYPE=0 4: KOZAI EPHTYPE=2: BROUWER)
let XA_TLE_REVNUM        = 26    // REVOLUTION NUMBER AT EPOCH
let XA_TLE_ELSETNUM      = 30    // ELEMENT SET NUMBER

// CSV (OR TLE-XP EPHEMTYPE=4) SPECIFIC FIELDS
let XA_TLE_ORGSATNUM     = 31    // ORIGINAL SATELLITE NUMBER
let XA_TLE_BTERM         = 32    // SP/SGP4-XP BALLISTIC COEFFICIENT (M2/KG)
let XA_TLE_OBSTIME       = 33    // TIME OF LAST OBSERVATION RELATIVE TO EPOCH +/- FRACTIONAL DAYS
let XA_TLE_EGR           = 34    // LAST CALCULATED ERROR GROWTH RATE (KM/DAY)
let XA_TLE_EDR           = 35    // LAST CALCULATED ENERGY DISSIPATION RATE (W/KG)
let XA_TLE_VISMAG        = 36    // MEDIAN VISMAG
let XA_TLE_RCS           = 37    // MEDIAN RCS - DIAMETER IN CENTIMETERS (CM)

// CSV (OR TLE-XP EPHEMTYPE=4)
let XA_TLE_AGOMGP        = 38    // SOLAR RADIATION PRESSURE COEFFICIENT GP (M2/KG)


// SP SPECIFIC FIELDS
let XA_TLE_SP_BTERM      =  2    // SP BALLISTIC COEFFICIENT (M2/KG)
let XA_TLE_SP_OGPARM     =  3    // SP OUTGASSING PARAMETER (KM/S2)
let XA_TLE_SP_AGOM       =  4    // SP RADIATION PRESSURE COEFFICIENT

let XA_TLE_SIZE          = 64

  // INDEXES OF TLE TEXT DATA IN AN ARRAY OF CHARS
let XS_TLE_SECCLASS_1   =  0    // SECURITY CLASSIFICATION OF LINE 1 AND LINE 2
let XS_TLE_SATNAME_12   =  1    // SATELLITE NAME
let XS_TLE_OBJTYPE_11   = 13    // OBJECT TYPE (PAYLOAD ROCKET BODY PLATFORM DEBRIS UNKNOWN)


let XS_TLE_SIZE         = 512

  // INDEXES OF DIFFERENT TLE FILE'S FORMATS
let XF_TLEFORM_ORG    =  0    // ORIGINAL TLE FORMAT
let XF_TLEFORM_CSV    =  1    // CSV FORMAT

